# Generated by Django 6.1 on 2026-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Sides', 'Sides'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=20),
        ),
    ]
